#!/usr/bin/env python3
"""Generates builds/door3x3_v4.build: the v3 mechanism + decoration.
Decor is only placed where it can't glue to slime/honey, power a piston, or block a required air cell."""
import itertools
OFF=8; W=16; Z=6; Y=8
g={}
def s(x,y,z,c): g[(x,y,z)]=c
# ---------- mechanism (identical to v3) ----------
for x in range(-8,8):
    for z in range(Z): s(x,0,z,'S')
for x in range(-3,5): s(x,0,1,'O')
for y in (1,2,3): s(-2,y,1,'Y'); s(-1,y,1,'Y')
s(-3,2,1,'E'); s(-2,4,1,'E'); s(-1,4,1,'Y')
for y in (1,2,3): s(3,y,1,'H')
s(4,2,1,'W')
for p in [(-3,1,1),(-3,3,1),(4,1,1),(4,3,1),(2,4,1),(3,4,1)]: s(*p,'O')
for x in range(-2,4): s(x,5,1,'O')
for x in (4,5): s(x,5,1,'S')
for x in range(-2,6): s(x,6,1,'D')
s(6,4,1,'S'); s(6,5,1,'D'); s(6,4,2,'S'); s(6,5,2,'r'); s(6,4,3,'S'); s(6,5,3,'r')
for x in range(-7,7): s(x,4,4,'S'); s(x,5,4,'D')
s(2,5,4,'q')
s(5,3,3,'S'); s(5,4,3,'D'); s(5,2,2,'S'); s(5,3,2,'D'); s(5,2,1,'S'); s(5,3,1,'D'); s(5,2,3,'l')
s(-3,4,3,'S'); s(-3,5,3,'n'); s(-3,4,2,'S'); s(-3,5,2,'D'); s(-3,4,1,'D')
for x in (-4,-5,-6): s(x,4,2,'S'); s(x,5,2,'w')
s(-7,4,2,'S'); s(-7,5,2,'D'); s(-7,4,3,'S'); s(-7,5,3,'D')
mech=dict(g)
# ---------- safety zones ----------
sticky=set()
for y in (1,2,3):
    for x in range(-2,2): sticky.add((x,y,1))       # slime slab travel
    for x in (2,3): sticky.add((x,y,1))              # honey travel
for x in range(-1,2): sticky.add((x,4,1))            # tab travel
pistons={(-3,2,1),(-2,4,1),(-1,4,1),(4,2,1)}
def nb(p):
    x,y,z=p
    return [(x+1,y,z),(x-1,y,z),(x,y+1,z),(x,y-1,z),(x,y,z+1),(x,y,z-1)]
danger=set()
for p in sticky|pistons:
    danger.add(p); danger.update(nb(p))
keep_air={(-3,5,1),(6,6,1),(5,5,3),(5,4,2),(-2,4,1),(0,4,1),(1,4,1)}|sticky
def decor(p,c):
    if p in g or p in keep_air: return
    if p in danger and c not in ('O','C'): return
    g[p]=c
# ---------- decoration ----------
# floor checker (leave the obsidian strip)
for x in range(-8,8):
    for z in range(Z):
        if z==1 and -3<=x<=4: continue
        g[(x,0,z)]='B' if (x+z)%2==0 else 'P'
# crying obsidian accents on the frame + strip
for p in [(-3,1,1),(-3,3,1),(4,1,1),(4,3,1),(2,4,1),(3,4,1),(0,5,1),(2,5,1)]: g[p]='C'
for x in range(-3,5):
    if x%2==0: g[(x,0,1)]='C'
# wall row z=1
for y in range(1,8):
    for x in list(range(-8,-3))+[6,7]: decor((x,y,1),'B')
for x in range(-8,8): decor((x,7,1),'B')
for x in range(-8,8):
    for y in (6,):
        decor((x,y,1),'B')
for p in [(5,1,1),(5,4,1)]: decor(p,'B')
# beam cap + south wall
for x in range(-7,7):
    decor((x,6,4),'B')
    for y in (4,5,6): decor((x,y,5),'B')
# west + east circuit caps
for x in range(-7,-2):
    for z in (2,3): decor((x,6,z),'B')
for z in (2,3): decor((6,6,z),'B')
# end walls of the beam
for y in (4,5,6): decor((7,y,4),'B'); decor((-8,y,4),'B')
# lanterns on the floor by the door (front and back)
for p in [(-5,1,0),(7,1,0),(-5,1,2),(7,1,3)]: decor(p,'L')
# ---------- write ----------
hdr='''# 3x3 piston door, v4: v3 mechanism + decoration. Generated by gen_door3x3.py.
# 16 wide (x), 6 deep (z), 8 tall. doorway x=8..10. lever on the back of the east wall (ON = closed).
# crying obsidian frame/accents are immovable, so they don't glue to slime/honey.
palette:
O obsidian
C crying_obsidian
S smooth_stone
B stone_bricks
P polished_andesite
L lantern[hanging=false]
Y slime_block
H honey_block
E sticky_piston[facing=east]
W sticky_piston[facing=west]
D redstone_wire
n repeater[facing=south,delay=1]
r repeater[facing=south,delay=4]
w repeater[facing=west,delay=4]
q repeater[facing=east,delay=1]
l lever[face=wall,facing=south,powered=false]
'''
out=[hdr]
for y in range(Y):
    out.append(f"layer {y}")
    for z in range(Z):
        out.append("".join(g.get((x,y,z),'.') for x in range(-8,8)))
    out.append("")
open("minecraft/builds/door3x3_v4.build","w").write("\n".join(out))
# sanity: mechanism cells unchanged
bad=[p for p,c in mech.items() if g.get(p)!=c and not (p[1]==0) and not (c=='O' and g.get(p)=='C')]
print("mechanism cells altered:",bad)
